---
name: Release

env:
  ENABLE_PYPI_PUBLISH: true
  ENABLE_TEST_PYPI_PUBLISH: false
  RELEASE_PYTHON_VERSION: "3.12"
  RELEASE_POETRY_VERSION: "2.0"

on:
  push:
    tags:
      - '*'

jobs:
  Publish:
    name: Publish package for ${{ github.ref_name }}

    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/safeway-coupons
    permissions:
      id-token: write

    steps:
      - name: üíæ Check out repository
        uses: actions/checkout@v4

      - name: üêç Set up Python project with Poetry
        uses: ./.github/workflows/actions/python-poetry
        with:
          python_version: ${{ env.RELEASE_PYTHON_VERSION }}
          poetry_version: ${{ env.RELEASE_POETRY_VERSION }}

      - name: üî• Test
        run: poetry run poe test

      - name: üöí Create test summary
        uses: test-summary/action@v1
        if: success() || failure()
        with:
          paths: ./.pytest_results.xml

      - name: üì¶ Build package
        if: |
          env.ENABLE_PYPI_PUBLISH == 'true'
          || env.ENABLE_TEST_PYPI_PUBLISH == 'true'
        run: poetry build

      - name: üîº Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: ${{ env.ENABLE_TEST_PYPI_PUBLISH == 'true' }}
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true

      - name: ‚ò¢Ô∏è Publish to PyPI
        if: ${{ env.ENABLE_PYPI_PUBLISH == 'true' }}
        uses: pypa/gh-action-pypi-publish@release/v1

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
